In [1]:
numero = 0
while numero < 6:
  print(numero)
  numero += 1

0
1
2
3
4
5


In [2]:
soma = 0
numero = 0
while numero <= 6:
  soma += numero
  numero +=1
  print(numero)

print(soma)

1
2
3
4
5
6
7
21


In [3]:
while True:
  try:
    numero = int(input("Informe um número: "))
  except:
    print("O número deve ser um inteiro")
  if numero >=20:
    print("Numero Maior que 20")
    break


Informe um número: 8
Informe um número: 4
Informe um número: 3
Informe um número: 2
Informe um número: 6
Informe um número: 21
Numero Maior que 20


In [4]:
from IPython.core import error
while True:
  dic = {}
  try:
    nome = input("Informe o nome do aluno: ")
    if not isinstance(nome, str):
      raise ValueError("O nome deve ser uma string.")

    nota = float(input("Informe a nota do aluno: "))
    if nota < 0 or nota > 100:
      raise ValueError("A nota deve ser um número entre 0 e 100.")

    dic[nome] = dic[nota]

    with open("Arquivo.txt", "a") as ar:
      ar.write(dic, "\n")

  except:
    pass

  per = input("Deseja continuar? S/N: ")
  per.upper()

  if per == "S":
    break


Informe o nome do aluno: Maria
Informe a nota do aluno: 9.5
Deseja continuar? S/N: Carla
Informe o nome do aluno: 7.6
Informe a nota do aluno: Bruna
Deseja continuar? S/N: 4.3
Informe o nome do aluno: Kaio
Informe a nota do aluno: 8.7
Deseja continuar? S/N: S


In [5]:
x = open("Arquivo.txt")

In [6]:
l = x.readlines()

In [7]:
for a in l:
  print(a)

Italo, 8.5

Maria, 9.6

Carla, 4.5

Bruna, 9.6

Barb, 4.8



In [8]:
x

<_io.TextIOWrapper name='Arquivo.txt' mode='r' encoding='cp1252'>

In [9]:
for i in range(1,10):
  print(f'{1} x 3 = {i * 3}')

1 x 3 = 3
1 x 3 = 6
1 x 3 = 9
1 x 3 = 12
1 x 3 = 15
1 x 3 = 18
1 x 3 = 21
1 x 3 = 24
1 x 3 = 27


In [10]:
print([x*3 for x in range(1,10)])

[3, 6, 9, 12, 15, 18, 21, 24, 27]


In [11]:
l = [x*3 for x in range(1,10)]

In [12]:
n = map(lambda x : x/2, l)

In [13]:
n = list(n)

In [14]:
print(list(n))

[1.5, 3.0, 4.5, 6.0, 7.5, 9.0, 10.5, 12.0, 13.5]


In [15]:
print(sum(n) / len(n))

7.5


In [16]:
def adivinha_proximo_numero(lista):
  """
  Adivina o próximo número de uma lista.

  Args:
    lista: Uma lista de números.

  Returns:
    O número que a IA acha que é o próximo.
  """

  # Calcula a diferença entre os elementos da lista.
  diferencas = [b - a for a, b in zip(lista[:-1], lista[1:])]

  # Calcula a média das diferenças.
  media_diferenca = sum(diferencas) / len(diferencas)

  # Adiciona a média da diferença ao último elemento da lista.
  proximo_numero = lista[-1] + media_diferenca

  return proximo_numero


lista = [1.5, 3.0, 4.5, 6.0, 7.5, 9.0, 10.5, 12.0, 13.5]

proximo_numero = adivinha_proximo_numero(lista)

print(proximo_numero)

15.0


In [17]:
dic = {x: x**2 for x in range(1,100)}

In [18]:
print(dic)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100, 11: 121, 12: 144, 13: 169, 14: 196, 15: 225, 16: 256, 17: 289, 18: 324, 19: 361, 20: 400, 21: 441, 22: 484, 23: 529, 24: 576, 25: 625, 26: 676, 27: 729, 28: 784, 29: 841, 30: 900, 31: 961, 32: 1024, 33: 1089, 34: 1156, 35: 1225, 36: 1296, 37: 1369, 38: 1444, 39: 1521, 40: 1600, 41: 1681, 42: 1764, 43: 1849, 44: 1936, 45: 2025, 46: 2116, 47: 2209, 48: 2304, 49: 2401, 50: 2500, 51: 2601, 52: 2704, 53: 2809, 54: 2916, 55: 3025, 56: 3136, 57: 3249, 58: 3364, 59: 3481, 60: 3600, 61: 3721, 62: 3844, 63: 3969, 64: 4096, 65: 4225, 66: 4356, 67: 4489, 68: 4624, 69: 4761, 70: 4900, 71: 5041, 72: 5184, 73: 5329, 74: 5476, 75: 5625, 76: 5776, 77: 5929, 78: 6084, 79: 6241, 80: 6400, 81: 6561, 82: 6724, 83: 6889, 84: 7056, 85: 7225, 86: 7396, 87: 7569, 88: 7744, 89: 7921, 90: 8100, 91: 8281, 92: 8464, 93: 8649, 94: 8836, 95: 9025, 96: 9216, 97: 9409, 98: 9604, 99: 9801}


In [19]:
print(dic[16])

256


In [20]:
lista = map(lambda x, y: y / x, zip(dic.keys(), dic.values()))

In [21]:
import numpy as np


In [22]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__packag

In [23]:
n = [int(x) for x in range(1,100)]
n1 = [int(x ** 2) for x in range(1,100)]

In [24]:
import numpy as np

n = [int(x) for x in range(1, 100)]
n1 = [int(x ** 2) for x in range(1, 100)]

num = np.column_stack((n, n1))


In [25]:
print(num)

[[   1    1]
 [   2    4]
 [   3    9]
 [   4   16]
 [   5   25]
 [   6   36]
 [   7   49]
 [   8   64]
 [   9   81]
 [  10  100]
 [  11  121]
 [  12  144]
 [  13  169]
 [  14  196]
 [  15  225]
 [  16  256]
 [  17  289]
 [  18  324]
 [  19  361]
 [  20  400]
 [  21  441]
 [  22  484]
 [  23  529]
 [  24  576]
 [  25  625]
 [  26  676]
 [  27  729]
 [  28  784]
 [  29  841]
 [  30  900]
 [  31  961]
 [  32 1024]
 [  33 1089]
 [  34 1156]
 [  35 1225]
 [  36 1296]
 [  37 1369]
 [  38 1444]
 [  39 1521]
 [  40 1600]
 [  41 1681]
 [  42 1764]
 [  43 1849]
 [  44 1936]
 [  45 2025]
 [  46 2116]
 [  47 2209]
 [  48 2304]
 [  49 2401]
 [  50 2500]
 [  51 2601]
 [  52 2704]
 [  53 2809]
 [  54 2916]
 [  55 3025]
 [  56 3136]
 [  57 3249]
 [  58 3364]
 [  59 3481]
 [  60 3600]
 [  61 3721]
 [  62 3844]
 [  63 3969]
 [  64 4096]
 [  65 4225]
 [  66 4356]
 [  67 4489]
 [  68 4624]
 [  69 4761]
 [  70 4900]
 [  71 5041]
 [  72 5184]
 [  73 5329]
 [  74 5476]
 [  75 5625]
 [  76 5776]
 [  77 5929]

In [26]:
num1 = np.array(([1,2,3,4,5,6],[7,8,9,10,11,12]))

In [27]:
num1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [28]:
num = np.array(([int(x) for x in range(1,100)], [int(x **2) for x in range(1,100)]))

In [29]:
n = np.array([[1,2,3], [4,5,6]])

In [30]:
n

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
print((num[0][10]), (num[1][10]))

11 121


In [32]:
num.shape #Retorna o formato o array

(2, 99)

In [33]:
for i in range(num.shape[0]):
  print(num[i])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]
[   1    4    9   16   25   36   49   64   81  100  121  144  169  196
  225  256  289  324  361  400  441  484  529  576  625  676  729  784
  841  900  961 1024 1089 1156 1225 1296 1369 1444 1521 1600 1681 1764
 1849 1936 2025 2116 2209 2304 2401 2500 2601 2704 2809 2916 3025 3136
 3249 3364 3481 3600 3721 3844 3969 4096 4225 4356 4489 4624 4761 4900
 5041 5184 5329 5476 5625 5776 5929 6084 6241 6400 6561 6724 6889 7056
 7225 7396 7569 7744 7921 8100 8281 8464 8649 8836 9025 9216 9409 9604
 9801]


In [34]:
num = np.array([[int(x) for x in range(1,50)], [int(x**2) for x in range(1,50)]])

In [35]:
num.shape

(2, 49)

In [36]:
num[1][23]

576

In [37]:
for i in range(num.shape[0]):
  print(num[i])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49]
[   1    4    9   16   25   36   49   64   81  100  121  144  169  196
  225  256  289  324  361  400  441  484  529  576  625  676  729  784
  841  900  961 1024 1089 1156 1225 1296 1369 1444 1521 1600 1681 1764
 1849 1936 2025 2116 2209 2304 2401]


In [38]:
n = np.array([[1,2,3],
             [4,5,6]])

In [39]:
n

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
n.shape

(2, 3)

In [41]:
n[1][2]

6

In [42]:
n[0]

array([1, 2, 3])

In [43]:
n[1]

array([4, 5, 6])

In [44]:
for i in range(n.shape[0]):
  print(n[i])

[1 2 3]
[4 5 6]


In [45]:
for i in range(n.shape[0]):
  print(n[i])
  for j in range(n.shape[1]):
    print(n[i][j])

[1 2 3]
1
2
3
[4 5 6]
4
5
6


In [46]:
n.shape[0] #Retorna o número de colunas no meu array

2

In [47]:
n.shape[1] # Retorna o número de linhas

3

In [48]:
n = [1,2,3]
n1 = [3,4,5]
n2 = [6,7,8]

In [49]:
no = np.array([n,n2,n1])

In [50]:
no.shape

(3, 3)

In [51]:
for i in range(no.shape[0]):
  print(n[i])

1
2
3


In [52]:
len(n)

3

In [53]:
lista = []
n = 0
while n < 5:
  j = int(input("Informe um número inteiro: "))
  lista.append(j)
  n += 1

Informe um número inteiro: 6
Informe um número inteiro: 5
Informe um número inteiro: 4
Informe um número inteiro: 3
Informe um número inteiro: 6


In [54]:
soma = 0
for i in lista:
  soma += i

In [55]:
soma

24

In [56]:
num = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [57]:
num

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
num.shape[0]

3

In [59]:
num.shape[1]

3

In [60]:
soma = 0
for i in range(num.shape[1]):
  print(i)
  soma += num[i]

0
1
2


In [61]:
print(sum(soma))

45


In [62]:
n = []
for _ in range(1,10):
  n.append(int(input("Informe número inteiro: ")))

n = list(map(lambda x: x*2, n))

Informe número inteiro: 7
Informe número inteiro: 6
Informe número inteiro: 5
Informe número inteiro: 4
Informe número inteiro: 3
Informe número inteiro: 8
Informe número inteiro: 5
Informe número inteiro: 3
Informe número inteiro: 2


In [63]:
sum(n)

86

In [64]:
min(n)

4

In [65]:
from numpy.lib.function_base import average
average(n)

9.555555555555555

In [66]:
print(list(n))

[14, 12, 10, 8, 6, 16, 10, 6, 4]


In [67]:
medida = sum(n) / (sum(n) / 2)

In [68]:
medida

2.0

In [69]:
import os

In [70]:
os.listdir()

['.ipynb_checkpoints',
 'arquivo.txt',
 'Exercicios.ipynb',
 'meto.py',
 'metodos.py',
 'n.py',
 'Treino_01.ipynb',
 'Untitled.ipynb',
 '__pycache__']

In [73]:
dic = {}
for _ in range(1,6):
    nome = input("Informe o nome: ")
    nota = float(input("Informe a nota"))
    dic[nome] = nota

Informe o nome: Italo
Informe a nota6.5
Informe o nome: Maria
Informe a nota8.6
Informe o nome: Carlos
Informe a nota4.6
Informe o nome: Leticia
Informe a nota7.6
Informe o nome: Marta
Informe a nota9.7


In [74]:
dic["Italo"]

6.5

In [ ]:
for nome, nota in dic.items():
    print(f'Nome: {nome} - Nota: {nota}')

In [75]:
import datetime

In [76]:
datetime.date.today()

datetime.date(2023, 11, 12)

In [77]:
datetime.datetime.now()

datetime.datetime(2023, 11, 12, 9, 29, 22, 995539)

In [78]:
hora = datetime.date.today()

In [79]:
hora

datetime.date(2023, 11, 12)

In [80]:
hora.year

2023

In [81]:
hora.month

11

In [82]:
hora.day

12

In [83]:
data = datetime.datetime.now()

In [84]:
data

datetime.datetime(2023, 11, 12, 9, 29, 28, 586850)

In [85]:
dir(data)

['__add__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__ne__',
 '__new__',
 '__radd__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rsub__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 'astimezone',
 'combine',
 'ctime',
 'date',
 'day',
 'dst',
 'fold',
 'fromisocalendar',
 'fromisoformat',
 'fromordinal',
 'fromtimestamp',
 'hour',
 'isocalendar',
 'isoformat',
 'isoweekday',
 'max',
 'microsecond',
 'min',
 'minute',
 'month',
 'now',
 'replace',
 'resolution',
 'second',
 'strftime',
 'strptime',
 'time',
 'timestamp',
 'timetuple',
 'timetz',
 'today',
 'toordinal',
 'tzinfo',
 'tzname',
 'utcfromtimestamp',
 'utcnow',
 'utcoffset',
 'utctimetuple',
 'weekday',
 'year']

In [86]:
import random

In [87]:
for _ in range(1,10):
    print(random.randint(1,10))

7
7
1
4
3
5
2
8
6


In [88]:
for _ in range(1,10):
    print(random.randrange(0,10, 2)) #Terceiro atributo é o step

4
0
4
6
0
6
0
8
0


In [89]:
lista = [1,2,6,'tr', 8.2, 67, "bf", 6.5, 2]

In [90]:
for _ in range(0,10):
    print(random.choice(lista))

2
2
6
8.2
bf
2
2
tr
1
bf


In [91]:
import time as tm

In [92]:
dir(tm)

['_STRUCT_TM_ITEMS',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'altzone',
 'asctime',
 'ctime',
 'daylight',
 'get_clock_info',
 'gmtime',
 'localtime',
 'mktime',
 'monotonic',
 'monotonic_ns',
 'perf_counter',
 'perf_counter_ns',
 'process_time',
 'process_time_ns',
 'sleep',
 'strftime',
 'strptime',
 'struct_time',
 'thread_time',
 'thread_time_ns',
 'time',
 'time_ns',
 'timezone',
 'tzname']

In [93]:
tm.time()

1699792188.2018094

In [94]:
antes = tm.time()
lista = []
for i in range(0,10000):
    lista.append(random.randint(0,50))
    
depois = tm.time()

In [95]:
print(antes)

1699792188.931369


In [96]:
print(depois)

1699792188.9433293


In [97]:
print(antes - depois)

-0.011960268020629883


In [98]:
lista

[5,
 32,
 29,
 18,
 35,
 44,
 23,
 4,
 12,
 42,
 21,
 2,
 47,
 6,
 41,
 32,
 24,
 35,
 31,
 38,
 49,
 43,
 40,
 8,
 31,
 41,
 12,
 42,
 7,
 44,
 23,
 2,
 38,
 50,
 27,
 19,
 7,
 48,
 22,
 49,
 16,
 47,
 10,
 15,
 47,
 31,
 32,
 39,
 2,
 31,
 16,
 30,
 20,
 1,
 33,
 2,
 40,
 30,
 45,
 35,
 16,
 28,
 10,
 16,
 18,
 10,
 21,
 25,
 2,
 4,
 21,
 23,
 44,
 16,
 25,
 28,
 24,
 37,
 13,
 20,
 32,
 23,
 19,
 18,
 50,
 17,
 33,
 10,
 8,
 41,
 33,
 39,
 45,
 5,
 6,
 29,
 29,
 16,
 15,
 47,
 18,
 46,
 8,
 49,
 34,
 3,
 0,
 44,
 24,
 42,
 5,
 0,
 43,
 2,
 2,
 46,
 45,
 34,
 4,
 37,
 44,
 48,
 17,
 48,
 13,
 19,
 35,
 36,
 6,
 41,
 22,
 2,
 44,
 23,
 32,
 26,
 8,
 41,
 49,
 25,
 34,
 5,
 50,
 39,
 30,
 36,
 0,
 42,
 2,
 48,
 39,
 36,
 38,
 46,
 1,
 5,
 26,
 28,
 5,
 26,
 26,
 2,
 6,
 32,
 7,
 13,
 14,
 22,
 17,
 5,
 9,
 24,
 37,
 9,
 15,
 8,
 25,
 18,
 15,
 16,
 18,
 28,
 25,
 3,
 32,
 45,
 35,
 17,
 10,
 20,
 25,
 4,
 12,
 36,
 18,
 25,
 48,
 31,
 27,
 8,
 43,
 37,
 23,
 16,
 49,
 13,
 19,
 30,
 3,

In [99]:
from collections import Counter

In [100]:
lis = Counter(lista)

In [101]:
lis.most_common()

[(50, 219),
 (19, 219),
 (35, 215),
 (41, 214),
 (18, 212),
 (20, 211),
 (13, 211),
 (25, 209),
 (0, 208),
 (32, 207),
 (39, 207),
 (31, 203),
 (43, 202),
 (36, 202),
 (11, 202),
 (14, 201),
 (42, 200),
 (23, 199),
 (2, 199),
 (49, 199),
 (15, 198),
 (33, 198),
 (17, 198),
 (3, 197),
 (26, 196),
 (37, 195),
 (29, 194),
 (8, 194),
 (27, 194),
 (44, 193),
 (16, 192),
 (1, 192),
 (45, 192),
 (47, 191),
 (38, 191),
 (28, 191),
 (12, 190),
 (6, 189),
 (24, 189),
 (40, 189),
 (48, 187),
 (30, 187),
 (4, 185),
 (22, 184),
 (34, 184),
 (10, 181),
 (5, 180),
 (7, 180),
 (46, 180),
 (21, 179),
 (9, 171)]

In [102]:
intervalo = antes - depois

In [103]:
print(intervalo)

-0.011960268020629883


In [104]:
for i in range(1,10):
    print(i)
    tm.sleep(2)
    print("Indo para o próximo")

1
Indo para o próximo
2
Indo para o próximo
3
Indo para o próximo
4
Indo para o próximo
5
Indo para o próximo
6
Indo para o próximo
7
Indo para o próximo
8
Indo para o próximo
9
Indo para o próximo


In [105]:
import os

In [106]:
os.listdir()

['.ipynb_checkpoints',
 'arquivo.txt',
 'Exercicios.ipynb',
 'meto.py',
 'metodos.py',
 'n.py',
 'Treino_01.ipynb',
 'Untitled.ipynb',
 '__pycache__']

In [107]:
import meto

In [108]:
dir(meto)

['IsPalidromo',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'divisao',
 'soma']

In [109]:
print(meto.IsPalidromo("abccba"))

É um palidromo


In [110]:
print(meto.soma(5,6))

11


In [111]:
print(meto.IsPalidromo("anna"))

É um palidromo


In [112]:
print("anna"[::-1])

anna


In [113]:
import meto

In [114]:
print(meto.divisao(3,4))

0.75


# Tratamento de erros

NameError: Quando a váriavel não foi definida
TypeError: Tipos de dados incompatíveis
RuntimeError: Erro de execução
SyntaxError: Erro de digitação
ZeroDivisionError: Divisão por zero
IndexError: Índice fora da coleção

In [115]:
3 = 4 #SyntaxError

SyntaxError: cannot assign to literal here. Maybe you meant '==' instead of '='? (732916017.py, line 1)

In [116]:
3 == 4

False

In [118]:
print(f'Meu nome é {Sobrenome}') #NameError

NameError: name 'Sobrenome' is not defined

In [119]:
print(3/0) #ZeroDivisionError

ZeroDivisionError: division by zero

In [120]:
print(3/"a") #TypeError

TypeError: unsupported operand type(s) for /: 'int' and 'str'

In [121]:
lista.indexoff() #AttributeError

AttributeError: 'list' object has no attribute 'indexoff'

In [123]:
n = int(input("Informe um número inteiro: "))

Informe um número inteiro: 43


In [124]:
n = int(input("Informe um número inteiro: ")) #ValueError

Informe um número inteiro: a


ValueError: invalid literal for int() with base 10: 'a'

In [126]:
try:
    n = int(input("Informe um número inteiro: ")) 

except:
    print("Informe um número inteiro")
else:
    print("Valor digitado:", n)

Informe um número inteiro: 43
Valor digitado:  43


In [127]:
while True:
    try:
        n = int(input("Informe um número inteiro: "))
    except:
        print("Número inválido")
    else:
        print("O número digitado foi,", n)
        break

Informe um número inteiro: 34
O número digitado foi, 34


In [128]:
while True:
    try:
        n = int(input("Informe um número inteiro: "))
    except:
        print("Número inválido")
    else:
        print("O número digitado foi,", n)
        break

Informe um número inteiro: asd
Número inválido
Informe um número inteiro: b
Número inválido
Informe um número inteiro: a
Número inválido
Informe um número inteiro: r
Número inválido
Informe um número inteiro: 54.34
Número inválido
Informe um número inteiro: 54
O número digitado foi, 54


In [131]:
while True:
    try:
        p = int(input("Informe um número inteiro: "))
    except ValueError:
        print("Valor inválido")
    except KeyboardInterrupt:
        print("Finalizado pelo usuário")
        break
        
    else:
        print("Valor digitado é:",p)
        break

Informe um número inteiro: 34
Valor digitado é: 34


In [132]:
while True:
    try:
        p = int(input("Informe um número inteiro: "))
    except ValueError:
        print("Valor inválido")
    except KeyboardInterrupt:
        print("Finalizado pelo usuário")
        break
        
    else:
        print("Valor digitado é:",p)
        break

Informe um número inteiro: d
Valor inválido
Informe um número inteiro: s
Valor inválido
Informe um número inteiro: fs
Valor inválido
Informe um número inteiro: gfd
Valor inválido
Informe um número inteiro: a
Valor inválido
Informe um número inteiro: 4
Valor digitado é: 4


In [2]:
def erros():
    lista = []
    while True:
        try:
            n = float(input("Informe o primeiro número flutuante: "))
            n1 = float(input("Informe o segundo número flutuante"))
        except ValueError:
            print("Informe um número válido")
        except KeyboardInterrupt:
            print("Programa encerrado ")
        else: 
            lista.append(n)
            lista.append(n1)
        
        try:
            print(lista[0] / lista[1])
            break
        except ZeroDivisionError:
            print("Impossível dividir por zero")
            break
        except IndexError:
            print("Index não encontrado")
            break
        
    

In [3]:
erros()

Informe o primeiro número flutuante: 4.5
Informe o segundo número flutuante7.5
0.6


In [4]:
erros()

Informe o primeiro número flutuante: 6.5
Informe o segundo número flutuantea
Informe um número válido
Index não encontrado


In [11]:
with open("arquivo/arquivo.txt", "r") as txt:
    for linha in txt:
        print(linha)

Italo, 8.5

Maria, 9.6

Carla, 4.5

Bruna, 9.6

Barb, 4.8



In [8]:
import os
os.listdir()

['.ipynb_checkpoints',
 'arquivo',
 'Exercicios.ipynb',
 'meto.py',
 'metodos.py',
 'n.py',
 'Treino_01.ipynb',
 'Untitled.ipynb',
 '__pycache__']

In [10]:
os.listdir("arquivo")

['arquivo.txt']

In [12]:
with open("arquivo/arquivo.txt") as txt:
    r = txt.readlines()

In [13]:
r

['Italo, 8.5\n', 'Maria, 9.6\n', 'Carla, 4.5\n', 'Bruna, 9.6\n', 'Barb, 4.8\n']

In [14]:
r[2]

'Carla, 4.5\n'

In [15]:
with open('arquivo/arquivo_2.txt', 'w') as txt:
    txt.write("Ola a todos")

In [16]:
os.listdir('arquivo')

['arquivo.txt', 'arquivo_2.txt']

In [18]:
with open('arquivo/arquivo_2.txt', 'r') as txt:
    for linha in txt:
        print(linha)

Ola a todos


In [9]:
with open('arquivo/notas.txt', 'w') as txt:
    while True:
        try:
            nome = input("Informe um nome: ")
            nota = float(input("Informe uma nota: "))
            txt.write(f'{nome} : {nota}\n')
        except ValueError:
            break
            print("Valor informado está incorreto")
        except KeyboardInterrupt:
            break
            print("Encerrado pelo usuário") 
            


Informe um nome: Maria
Informe uma nota: 5.4
Informe um nome: Carlos
Informe uma nota: 8.7
Informe um nome: Kaique
Informe uma nota: 5.6
Informe um nome: Marta
Informe uma nota: 7.6
Informe um nome: Barbara
Informe uma nota: 8.1
Informe um nome: Sam
Informe uma nota: 9.5
Informe um nome: Luiz
Informe uma nota: 4.5


In [10]:
with open('arquivo/notas.txt', 'r') as txt:
    for linha in txt:
        print(linha)

Maria : 5.4

Carlos : 8.7

Kaique : 5.6

Marta : 7.6

Barbara : 8.1

Sam : 9.5

Luiz : 4.5



# Expressões regulares

### Busca sofisticada em string
### Procurar todas as palavras que começam com letra maiúscula ou minúscula 
### Que começam com 'a' e terminam com 'e'
### Procurar por e-mail, número de telefone, CEP's e etc

### Encontrar as posições de padrões dentro de uma string, se estes estiver presentes (métodos search)
### Encontrar se o começo de uma string é igual a um determinado padrão (método match)
### Encontrar todas as substrings em uma string que correspondam a um padrão (método findall)

In [ ]:
https://docs.python.org/pt-br/3/library/re.html# Documentação

In [18]:
lista = """Você nunca atende, você é maluca

Mas você nunca me atende
Você é maluca e me entende
Você é a única que vai ganhar música da minha pessoa pública daqui pra frente
Mas você nunca me atende
Você é maluca e me entende
Você é a única que vai ganhar música da minha pessoa pública daqui pra frente

Misturo fogo com gasolina
Tô sem minha peita de dar rolê
Volto sem peita, eu deixei com a mina
Tá com meu cheiro pra tu saber
Minha camiseta é a favorita
Então você tem que me devolver
Tá com meu cheiro na axila
Vitória, eu sei qual é o seu segredo
Mano, um dia eu fui na Disney
O Derek disse pra eu não usar listra
Briso amarelo porque combina
Algo bem quente num dia cinza
Toda essa moda é tão relativa
Antes da grana eu pegava mina
Com a minha camisa da Maresia
O que ela quer é adrenalina

Eu tenho um carro, já tive moto
Foda-se o topo
Não tô por falar quando eu entoco
Não dá pra falar que eu não me importo
Você é linda, me via em foto
Tem uma vírgula no seu corpo
Sei que elas dizem que eu não sou santo
Eu tô aqui pra botar um ponto
Lembra de mim no primeiro encontro?
Sei que eu mudei, 'cê num sabe o quanto
Mas eu ainda sou o que canto
Por isso me encontrou por todo canto
É pra você que eu trampo, mas eu preciso de um sindicato
Acho que ainda sou só um sujeito
Essa canção é meu predicado

Mas você nunca me atende
Você é maluca e me entende
Você é a única que vai ganhar música da minha pessoa pública daqui pra frente
Mas você nunca me atende
Você é maluca e me entende
Você é a única que vai ganhar música da minha pessoa pública daqui pra frente

Ei, ei, ei, ei, ei, ei
Eu dividi a capa do jornal com a Björk
Eu só pude ler no day off
Eletros do meu carro no poste
Todos querem a chave do cofre
A polícia não confia nos jovens
Os jovens não confiam em ninguém
Nós somos rebeldes
Dormi na sua casa de novo
Eu sei, você precisa de alguém
Me dê mais remédios
Me conte segredos

Jovens não confiam em ninguém
A era do medo, quem me disse foi um bebo no trem
Ninguém acredita no bem
O mal não é mais um agente secreto
Amar é pros fortes
Amargo, massa, gado, sorte, o Sol, o sal, tua vida, longa vida boa
Chega dessa vida tão corrida, adulta vida cobra, o tempo leva
Toda dor embora, tenho ótimas notícias, péssimas memórias
Boas histórias são tristes
Boas histórias são
A gente existe por obrigação e ainda insiste numa ligação

Que você nunca atende
Você é maluca, me entende
Única"""

In [19]:
lista = lista.split()

In [13]:
from collections import Counter

In [21]:
lista

['Você',
 'nunca',
 'atende,',
 'você',
 'é',
 'maluca',
 'Mas',
 'você',
 'nunca',
 'me',
 'atende',
 'Você',
 'é',
 'maluca',
 'e',
 'me',
 'entende',
 'Você',
 'é',
 'a',
 'única',
 'que',
 'vai',
 'ganhar',
 'música',
 'da',
 'minha',
 'pessoa',
 'pública',
 'daqui',
 'pra',
 'frente',
 'Mas',
 'você',
 'nunca',
 'me',
 'atende',
 'Você',
 'é',
 'maluca',
 'e',
 'me',
 'entende',
 'Você',
 'é',
 'a',
 'única',
 'que',
 'vai',
 'ganhar',
 'música',
 'da',
 'minha',
 'pessoa',
 'pública',
 'daqui',
 'pra',
 'frente',
 'Misturo',
 'fogo',
 'com',
 'gasolina',
 'Tô',
 'sem',
 'minha',
 'peita',
 'de',
 'dar',
 'rolê',
 'Volto',
 'sem',
 'peita,',
 'eu',
 'deixei',
 'com',
 'a',
 'mina',
 'Tá',
 'com',
 'meu',
 'cheiro',
 'pra',
 'tu',
 'saber',
 'Minha',
 'camiseta',
 'é',
 'a',
 'favorita',
 'Então',
 'você',
 'tem',
 'que',
 'me',
 'devolver',
 'Tá',
 'com',
 'meu',
 'cheiro',
 'na',
 'axila',
 'Vitória,',
 'eu',
 'sei',
 'qual',
 'é',
 'o',
 'seu',
 'segredo',
 'Mano,',
 'um',
 'dia

In [24]:
a = []
for i in lista:
    a.append(i.lower())

In [25]:
a

['você',
 'nunca',
 'atende,',
 'você',
 'é',
 'maluca',
 'mas',
 'você',
 'nunca',
 'me',
 'atende',
 'você',
 'é',
 'maluca',
 'e',
 'me',
 'entende',
 'você',
 'é',
 'a',
 'única',
 'que',
 'vai',
 'ganhar',
 'música',
 'da',
 'minha',
 'pessoa',
 'pública',
 'daqui',
 'pra',
 'frente',
 'mas',
 'você',
 'nunca',
 'me',
 'atende',
 'você',
 'é',
 'maluca',
 'e',
 'me',
 'entende',
 'você',
 'é',
 'a',
 'única',
 'que',
 'vai',
 'ganhar',
 'música',
 'da',
 'minha',
 'pessoa',
 'pública',
 'daqui',
 'pra',
 'frente',
 'misturo',
 'fogo',
 'com',
 'gasolina',
 'tô',
 'sem',
 'minha',
 'peita',
 'de',
 'dar',
 'rolê',
 'volto',
 'sem',
 'peita,',
 'eu',
 'deixei',
 'com',
 'a',
 'mina',
 'tá',
 'com',
 'meu',
 'cheiro',
 'pra',
 'tu',
 'saber',
 'minha',
 'camiseta',
 'é',
 'a',
 'favorita',
 'então',
 'você',
 'tem',
 'que',
 'me',
 'devolver',
 'tá',
 'com',
 'meu',
 'cheiro',
 'na',
 'axila',
 'vitória,',
 'eu',
 'sei',
 'qual',
 'é',
 'o',
 'seu',
 'segredo',
 'mano,',
 'um',
 'dia

In [26]:
contagem = Counter(a)

In [27]:
contagem

Counter({'você': 20,
         'nunca': 6,
         'atende,': 1,
         'é': 19,
         'maluca': 5,
         'mas': 6,
         'me': 16,
         'atende': 5,
         'e': 5,
         'entende': 5,
         'a': 13,
         'única': 5,
         'que': 14,
         'vai': 4,
         'ganhar': 4,
         'música': 4,
         'da': 6,
         'minha': 7,
         'pessoa': 4,
         'pública': 4,
         'daqui': 4,
         'pra': 9,
         'frente': 4,
         'misturo': 1,
         'fogo': 1,
         'com': 6,
         'gasolina': 1,
         'tô': 3,
         'sem': 2,
         'peita': 1,
         'de': 5,
         'dar': 1,
         'rolê': 1,
         'volto': 1,
         'peita,': 1,
         'eu': 17,
         'deixei': 1,
         'mina': 2,
         'tá': 2,
         'meu': 4,
         'cheiro': 2,
         'tu': 1,
         'saber': 1,
         'camiseta': 1,
         'favorita': 1,
         'então': 1,
         'tem': 2,
         'devolver': 1,
         'na

In [30]:
contagem.most_common()

[('você', 20),
 ('é', 19),
 ('eu', 17),
 ('me', 16),
 ('que', 14),
 ('a', 13),
 ('o', 10),
 ('pra', 9),
 ('não', 9),
 ('minha', 7),
 ('um', 7),
 ('nunca', 6),
 ('mas', 6),
 ('da', 6),
 ('com', 6),
 ('no', 6),
 ('maluca', 5),
 ('atende', 5),
 ('e', 5),
 ('entende', 5),
 ('única', 5),
 ('de', 5),
 ('ei,', 5),
 ('vai', 4),
 ('ganhar', 4),
 ('música', 4),
 ('pessoa', 4),
 ('pública', 4),
 ('daqui', 4),
 ('frente', 4),
 ('meu', 4),
 ('por', 4),
 ('do', 4),
 ('tô', 3),
 ('na', 3),
 ('sei', 3),
 ('em', 3),
 ('sou', 3),
 ('ainda', 3),
 ('jovens', 3),
 ('ninguém', 3),
 ('vida', 3),
 ('sem', 2),
 ('mina', 2),
 ('tá', 2),
 ('cheiro', 2),
 ('tem', 2),
 ('seu', 2),
 ('dia', 2),
 ('disse', 2),
 ('bem', 2),
 ('num', 2),
 ('toda', 2),
 ('essa', 2),
 ('tão', 2),
 ('tenho', 2),
 ('falar', 2),
 ('canto', 2),
 ('só', 2),
 ('confiam', 2),
 ('mais', 2),
 ('boas', 2),
 ('histórias', 2),
 ('são', 2),
 ('atende,', 1),
 ('misturo', 1),
 ('fogo', 1),
 ('gasolina', 1),
 ('peita', 1),
 ('dar', 1),
 ('rolê', 1),
 (

In [ ]:
## Metacaracteres

.- - Qualquer caractere (exceto linha nova)
\w - Qualquer caracterealfanumérico
\W - Qualquer caractere não-alfanúmerico
\d - Qualquer caractere que seja um dígito (0, 9)
\D - Qualquer caractere que não seja um dígito
\s - Espaço em branco
^- - Começa com
$  - Termina com
"\" - Usado antes de metacaracteres por especificar letra

In [ ]:
## Quantificadores

Permitem determinar como e quantas vezes os metacaracteres aparecem

[] - Opcional entre os que estão dentro dos colchetes
() - Captura grupos de caracteres
*- - de zero a mais vezes
? - Zero ou uma vez
+ - uma ou mais vezes
{m,n} - de m a n vezes
| - OU

In [ ]:
gabiel.luis@gmail.com
marta_futblk@gmail.com
carlos_kaio@gmail.com

#Expressões regulares que detecta e-mail

\w+@\w+\.w+

## Função search

In [41]:
import re

In [42]:
frase = 'Ola, meu número de telefone é (43)98545-9858'

In [43]:
re.search('\(\d{2}\)\d{4,5}-\d{4}', frase)

<re.Match object; span=(30, 44), match='(43)98545-9858'>

In [54]:
email = " Meu email é kaique_luix1997@gmail.com"

In [48]:
frase = 'A placa do carro é PRT-8456'

In [49]:
re.search('[A-Z]{3}-\d{4}', frase)

<re.Match object; span=(19, 27), match='PRT-8456'>

In [51]:
re.search('[A-Za-z]{3}-\d{4}', frase)

<re.Match object; span=(19, 27), match='PRT-8456'>

In [55]:
re.search('\w+@\w+\.', email)

<re.Match object; span=(13, 35), match='kaique_luix1997@gmail.'>

## Função match

Verifica se uma expressão regular está no ínicio de um texto

In [56]:
print(re.match('[A-Z]{3}-\d{4}', frase)) #Esse padrão não está no ínicio da string 

None


In [60]:
frase2 = 'PRT-5584 está é a placa'

In [61]:
print(re.match('[A-Z]{3}-\d{4}', frase2)) #Esse padrão está no ínicio da string 

<re.Match object; span=(0, 8), match='PRT-5584'>


## Função findall

In [ ]:
## Encontra várias ocorrencias de um padrão

In [62]:
frase3 = 'Meu número de telefone atual é (62)98452-9865, o antigo era (62)98412-6588'

In [66]:
re.findall('\(\d{2}\)\d{4,5}-\d{4}', frase3)

['(62)98452-9865', '(62)98412-6588']

In [67]:
email = '''
email: testeyitr@gmail.com
email: None
email: kaiquetrp@gmail.com
email: carlos1998@gmail.com
email: barbara_silva89@gmail.com
email: maria_limas@gmail.com
'''

In [73]:
lista_email = re.findall('\w+@\w+\.\w*', email) #* Significa que pode aparecer uma ou varias vezes

In [74]:
lista_email

['testeyitr@gmail.com',
 'kaiquetrp@gmail.com',
 'carlos1998@gmail.com',
 'barbara_silva89@gmail.com',
 'maria_limas@gmail.com']

In [75]:
dir(re)

['A',
 'ASCII',
 'DEBUG',
 'DOTALL',
 'I',
 'IGNORECASE',
 'L',
 'LOCALE',
 'M',
 'MULTILINE',
 'Match',
 'Pattern',
 'RegexFlag',
 'S',
 'Scanner',
 'T',
 'TEMPLATE',
 'U',
 'UNICODE',
 'VERBOSE',
 'X',
 '_MAXCACHE',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '__version__',
 '_cache',
 '_compile',
 '_compile_repl',
 '_expand',
 '_locale',
 '_pickle',
 '_special_chars_map',
 '_subx',
 'compile',
 'copyreg',
 'enum',
 'error',
 'escape',
 'findall',
 'finditer',
 'fullmatch',
 'functools',
 'match',
 'purge',
 'search',
 'split',
 'sre_compile',
 'sre_parse',
 'sub',
 'subn',
 'template']

In [76]:
lista

['Você',
 'nunca',
 'atende,',
 'você',
 'é',
 'maluca',
 'Mas',
 'você',
 'nunca',
 'me',
 'atende',
 'Você',
 'é',
 'maluca',
 'e',
 'me',
 'entende',
 'Você',
 'é',
 'a',
 'única',
 'que',
 'vai',
 'ganhar',
 'música',
 'da',
 'minha',
 'pessoa',
 'pública',
 'daqui',
 'pra',
 'frente',
 'Mas',
 'você',
 'nunca',
 'me',
 'atende',
 'Você',
 'é',
 'maluca',
 'e',
 'me',
 'entende',
 'Você',
 'é',
 'a',
 'única',
 'que',
 'vai',
 'ganhar',
 'música',
 'da',
 'minha',
 'pessoa',
 'pública',
 'daqui',
 'pra',
 'frente',
 'Misturo',
 'fogo',
 'com',
 'gasolina',
 'Tô',
 'sem',
 'minha',
 'peita',
 'de',
 'dar',
 'rolê',
 'Volto',
 'sem',
 'peita,',
 'eu',
 'deixei',
 'com',
 'a',
 'mina',
 'Tá',
 'com',
 'meu',
 'cheiro',
 'pra',
 'tu',
 'saber',
 'Minha',
 'camiseta',
 'é',
 'a',
 'favorita',
 'Então',
 'você',
 'tem',
 'que',
 'me',
 'devolver',
 'Tá',
 'com',
 'meu',
 'cheiro',
 'na',
 'axila',
 'Vitória,',
 'eu',
 'sei',
 'qual',
 'é',
 'o',
 'seu',
 'segredo',
 'Mano,',
 'um',
 'dia

In [84]:
lista = ["nome1@dominio.com", "nome2@dominio.com", "nome3@dominio.com", "nome4@dominio.com", "nome5@dominio.com",
          "nome6@dominio.com", "nome7@dominio.com", "nome8@dominio.com", "nome9@dominio.com", "nome10@dominio.com",
          "nome11@dominio.com", "nome12@dominio.com", "nome13@dominio.com", "nome14@dominio.com", "nome15@dominio.com",
          "nome16@dominio.com", "nome17@dominio.com", "nome18@dominio.com", "nome19@dominio.com", "nome20@dominio.com",
          "nome21@dominio.com", "nome22@dominio.com", "nome23@dominio.com", "nome24@dominio.com", "nome25@dominio.com",
          "nome26@dominio.com", "nome27@dominio.com", "nome28@dominio.com", "nome29@dominio.com", "nome30@dominio.com",
          "nome31@dominio.com", "nome32@dominio.com", "nome33@dominio.com", "nome34@dominio.com", "nome35@dominio.com",
          "nome36@dominio.com", "nome37@dominio.com", "nome38@dominio.com", "nome39@dominio.com", "nome40@dominio.com",
          "nome41@dominio.com", "nome42@dominio.com", "nome43@dominio.com", "nome44@dominio.com", "nome45@dominio.com",
          "nome46@dominio.com", "nome47@dominio.com", "nome48@dominio.com", "nome49@dominio.com", "nome50@dominio.com"]


In [85]:
lista

['nome1@dominio.com',
 'nome2@dominio.com',
 'nome3@dominio.com',
 'nome4@dominio.com',
 'nome5@dominio.com',
 'nome6@dominio.com',
 'nome7@dominio.com',
 'nome8@dominio.com',
 'nome9@dominio.com',
 'nome10@dominio.com',
 'nome11@dominio.com',
 'nome12@dominio.com',
 'nome13@dominio.com',
 'nome14@dominio.com',
 'nome15@dominio.com',
 'nome16@dominio.com',
 'nome17@dominio.com',
 'nome18@dominio.com',
 'nome19@dominio.com',
 'nome20@dominio.com',
 'nome21@dominio.com',
 'nome22@dominio.com',
 'nome23@dominio.com',
 'nome24@dominio.com',
 'nome25@dominio.com',
 'nome26@dominio.com',
 'nome27@dominio.com',
 'nome28@dominio.com',
 'nome29@dominio.com',
 'nome30@dominio.com',
 'nome31@dominio.com',
 'nome32@dominio.com',
 'nome33@dominio.com',
 'nome34@dominio.com',
 'nome35@dominio.com',
 'nome36@dominio.com',
 'nome37@dominio.com',
 'nome38@dominio.com',
 'nome39@dominio.com',
 'nome40@dominio.com',
 'nome41@dominio.com',
 'nome42@dominio.com',
 'nome43@dominio.com',
 'nome44@dominio.com

In [89]:
print(re.findall('\@\w+', lista))

TypeError: expected string or bytes-like object

In [91]:
a = 'If one or more capturing groups are present in the pattern, return'
print(re.search(r'in', a))

<re.Match object; span=(21, 23), match='in'>


In [92]:
print(a[21:23])

in


In [94]:
print(re.findall(r'a', a))

['a', 'a', 'a']


In [95]:
print(len(re.findall(r'a', a)))

3


In [97]:
re.sub(r' ', '-', a, count=1) #Subistitui somente o primeiro elemento que encontra

'If-one or more capturing groups are present in the pattern, return'

In [98]:
subistitue = re.compile(r'a')

In [99]:
subistitue.findall(a)

['a', 'a', 'a']

In [100]:
musica = """Você nunca atende, você é maluca

Mas você nunca me atende
Você é maluca e me entende
Você é a única que vai ganhar música da minha pessoa pública daqui pra frente
Mas você nunca me atende
Você é maluca e me entende
Você é a única que vai ganhar música da minha pessoa pública daqui pra frente

Misturo fogo com gasolina
Tô sem minha peita de dar rolê
Volto sem peita, eu deixei com a mina
Tá com meu cheiro pra tu saber
Minha camiseta é a favorita
Então você tem que me devolver
Tá com meu cheiro na axila
Vitória, eu sei qual é o seu segredo
Mano, um dia eu fui na Disney
O Derek disse pra eu não usar listra
Briso amarelo porque combina
Algo bem quente num dia cinza
Toda essa moda é tão relativa
Antes da grana eu pegava mina
Com a minha camisa da Maresia
O que ela quer é adrenalina

Eu tenho um carro, já tive moto
Foda-se o topo
Não tô por falar quando eu entoco
Não dá pra falar que eu não me importo
Você é linda, me via em foto
Tem uma vírgula no seu corpo
Sei que elas dizem que eu não sou santo
Eu tô aqui pra botar um ponto
Lembra de mim no primeiro encontro?
Sei que eu mudei, 'cê num sabe o quanto
Mas eu ainda sou o que canto
Por isso me encontrou por todo canto
É pra você que eu trampo, mas eu preciso de um sindicato
Acho que ainda sou só um sujeito
Essa canção é meu predicado

Mas você nunca me atende
Você é maluca e me entende
Você é a única que vai ganhar música da minha pessoa pública daqui pra frente
Mas você nunca me atende
Você é maluca e me entende
Você é a única que vai ganhar música da minha pessoa pública daqui pra frente

Ei, ei, ei, ei, ei, ei
Eu dividi a capa do jornal com a Björk
Eu só pude ler no day off
Eletros do meu carro no poste
Todos querem a chave do cofre
A polícia não confia nos jovens
Os jovens não confiam em ninguém
Nós somos rebeldes
Dormi na sua casa de novo
Eu sei, você precisa de alguém
Me dê mais remédios
Me conte segredos

Jovens não confiam em ninguém
A era do medo, quem me disse foi um bebo no trem
Ninguém acredita no bem
O mal não é mais um agente secreto
Amar é pros fortes
Amargo, massa, gado, sorte, o Sol, o sal, tua vida, longa vida boa
Chega dessa vida tão corrida, adulta vida cobra, o tempo leva
Toda dor embora, tenho ótimas notícias, péssimas memórias
Boas histórias são tristes
Boas histórias são
A gente existe por obrigação e ainda insiste numa ligação

Que você nunca atende
Você é maluca, me entende
Única"""

In [102]:
print(re.findall(r'Você|você|maluca|Maluca', musica)) #OU

['Você', 'você', 'maluca', 'você', 'Você', 'maluca', 'Você', 'você', 'Você', 'maluca', 'Você', 'você', 'Você', 'você', 'você', 'Você', 'maluca', 'Você', 'você', 'Você', 'maluca', 'Você', 'você', 'você', 'Você', 'maluca']


In [104]:
print(re.findall(r'.ocê|.aluca', musica)) #Ponto significa qualquer caracteres

['Você', 'você', 'maluca', 'você', 'Você', 'maluca', 'Você', 'você', 'Você', 'maluca', 'Você', 'você', 'Você', 'você', 'você', 'Você', 'maluca', 'Você', 'você', 'Você', 'maluca', 'Você', 'você', 'você', 'Você', 'maluca']


In [106]:
print(re.findall(r'[Vv]ocê|[Mm]aluca ', musica)) #[] Significa um conjunto de caracteres

['Você', 'você', 'você', 'Você', 'maluca ', 'Você', 'você', 'Você', 'maluca ', 'Você', 'você', 'Você', 'você', 'você', 'Você', 'maluca ', 'Você', 'você', 'Você', 'maluca ', 'Você', 'você', 'você', 'Você']


In [107]:
print(re.findall(r'[A-Za-z]ocê|[A-Za-z]aluca ', musica)) #[] Significa um conjunto de caracteres

['Você', 'você', 'você', 'Você', 'maluca ', 'Você', 'você', 'Você', 'maluca ', 'Você', 'você', 'Você', 'você', 'você', 'Você', 'maluca ', 'Você', 'você', 'Você', 'maluca ', 'Você', 'você', 'você', 'Você']


In [108]:
print(re.findall(r'vOcÊ|MalUcA ', musica))

[]


In [109]:
print(re.findall(r'vOcÊ|MalUcA ', musica, flags=re.I))

['Você', 'você', 'você', 'Você', 'maluca ', 'Você', 'você', 'Você', 'maluca ', 'Você', 'você', 'Você', 'você', 'você', 'Você', 'maluca ', 'Você', 'você', 'Você', 'maluca ', 'Você', 'você', 'você', 'Você']


In [119]:
numeros_telefone = [
    "Meu número é 11 99999-9999",
    "Meu número é 12 33333-3333",
    "Meu número é 13 44444-4444",
    "Meu número é 14 55555-5555",
    "Meu número é 15 66666-6666",
    "Meu número é 16 77777-7777",
    "Meu número é 17 88888-8888",
    "Meu número é 18 99999-9999",
    "Meu número é 19 99999-9999",
    "Meu número é 21 99999-9999",
    "Meu número é 22 99999-9999",
    "Meu número é 23 99999-9999",
    "Meu número é 24 99999-9999",
    "Meu número é 25 99999-9999",
    "Meu número é 26 99999-9999",
    "Meu número é 27 99999-9999",
    "Meu número é 28 99999-9999",
]


In [123]:
numeros_telefone_como_string = str(numeros_telefone)

In [127]:
numeros_telefone_como_string

"['Meu número é 11 99999-9999', 'Meu número é 12 33333-3333', 'Meu número é 13 44444-4444', 'Meu número é 14 55555-5555', 'Meu número é 15 66666-6666', 'Meu número é 16 77777-7777', 'Meu número é 17 88888-8888', 'Meu número é 18 99999-9999', 'Meu número é 19 99999-9999', 'Meu número é 21 99999-9999', 'Meu número é 22 99999-9999', 'Meu número é 23 99999-9999', 'Meu número é 24 99999-9999', 'Meu número é 25 99999-9999', 'Meu número é 26 99999-9999', 'Meu número é 27 99999-9999', 'Meu número é 28 99999-9999']"

In [126]:
print(re.findall(r"\+\d{2} [0-9]{4,5}-[0-9]{4}", numeros_telefone_como_string))

[]


In [131]:
class Aluno:
    def __init__(self, nome, nota1, nota2):
        self._nome = nome
        self._nota1 = nota1
        self._nota2 = nota2
        
    def passou(self):
        if (self._nota1 + self._nota2) / 2 > 6:
            print(f'{self._nome} foi aprovado com nota {(self._nota1 + self._nota2)/2}')
        else:
            print(f'{self._nome} foi reprovado com nota {(self._nota1 + self._nota2)/2}')

In [132]:
aluno = Aluno('Italo', 6.8, 9.8)

In [133]:
aluno.passou()

Italo foi aprovado com nota 8.3


In [134]:
aluno1 = Aluno('Maria', 6.3, 4.5)

In [135]:
aluno1.passou()

Maria foi reprovado com nota 5.4
